# Making a pipeline for model training in pytorch

- In this notebook we manually coded to understand how the flow works behind but this not right way to make a neural network in pytorch.
- Pytorch gives out box many components for training a model.

Code flow

 1. Load the dataset
 2. Basic preprocessing
 3. Training Process
   - Create the model
   - Forward pass
   - Loss calculation
   - Backprop
   - Parameters update
 4. Model evaluation

In [1]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

- Importing a dataset.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

- Droping unneeded columns such as id and unnamed in this dataset.

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

- Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

- Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.352723  ,  0.64325105, -1.35226297, ..., -1.37518718,
        -0.75217164, -0.58921275],
       [ 0.18072545, -1.0546021 ,  0.11976961, ...,  0.13846578,
         0.32013144, -0.1536087 ],
       [ 1.22336867,  0.63617666,  1.15955168, ...,  0.33326528,
         0.32013144, -0.47016227],
       ...,
       [-0.50306767,  0.70927867, -0.49679284, ..., -0.51837377,
        -1.01786097,  0.33740594],
       [ 0.27679555,  0.66211608,  0.21787775, ...,  0.56306781,
        -0.37034265, -0.32587528],
       [ 0.37851684,  0.06315122,  0.40013722, ...,  0.53871787,
        -0.11260808, -0.24577681]], shape=(455, 30))

In [9]:
y_train

553    B
347    B
134    M
88     B
517    M
      ..
502    B
384    B
163    B
54     M
131    M
Name: diagnosis, Length: 455, dtype: object

- Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,

- Numpy arrays to pytorch tensors.

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-1.3527,  0.6433, -1.3523,  ..., -1.3752, -0.7522, -0.5892],
        [ 0.1807, -1.0546,  0.1198,  ...,  0.1385,  0.3201, -0.1536],
        [ 1.2234,  0.6362,  1.1596,  ...,  0.3333,  0.3201, -0.4702],
        ...,
        [-0.5031,  0.7093, -0.4968,  ..., -0.5184, -1.0179,  0.3374],
        [ 0.2768,  0.6621,  0.2179,  ...,  0.5631, -0.3703, -0.3259],
        [ 0.3785,  0.0632,  0.4001,  ...,  0.5387, -0.1126, -0.2458]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [16]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad= True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

 - Important parameters

In [17]:
learning_rate = 0.1
epochs = 25

- Training pipeline

In [18]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 3.657330738622884
Epoch: 2, loss: 3.536873456831405
Epoch: 3, loss: 3.4132914438920676
Epoch: 4, loss: 3.287203373431186
Epoch: 5, loss: 3.1566054852478165
Epoch: 6, loss: 3.020302142983881
Epoch: 7, loss: 2.8803757271591977
Epoch: 8, loss: 2.732397402829262
Epoch: 9, loss: 2.580075241503143
Epoch: 10, loss: 2.4263977193334307
Epoch: 11, loss: 2.264694227252277
Epoch: 12, loss: 2.105495635216888
Epoch: 13, loss: 1.9494711826389377
Epoch: 14, loss: 1.7966502220939997
Epoch: 15, loss: 1.6511738087650898
Epoch: 16, loss: 1.5097714128782358
Epoch: 17, loss: 1.3745815242701096
Epoch: 18, loss: 1.2538600361269598
Epoch: 19, loss: 1.1491413524193315
Epoch: 20, loss: 1.0613397342037418
Epoch: 21, loss: 0.990408885359174
Epoch: 22, loss: 0.9351930068022605
Epoch: 23, loss: 0.8935801283826862
Epoch: 24, loss: 0.8629005228420334
Epoch: 25, loss: 0.8404023578705263


In [19]:
model.weights

tensor([[-0.3125],
        [ 0.3559],
        [ 0.4230],
        [ 0.3372],
        [ 0.1454],
        [-0.2906],
        [ 0.1705],
        [-0.1370],
        [ 0.4739],
        [ 0.2569],
        [-0.1231],
        [ 0.6780],
        [-0.1079],
        [-0.0560],
        [-0.0501],
        [-0.2589],
        [-0.2635],
        [ 0.0884],
        [ 0.6016],
        [-0.0609],
        [-0.2520],
        [-0.1963],
        [ 0.3685],
        [ 0.1902],
        [ 0.1328],
        [-0.1814],
        [ 0.0400],
        [-0.0735],
        [-0.2191],
        [ 0.0074]], dtype=torch.float64, requires_grad=True)

In [20]:
model.bias

tensor([-0.1159], dtype=torch.float64, requires_grad=True)

### Evaluation

In [21]:
# model evaluation

with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5196983814239502
