# Making a pipeline for model training in pytorch

- In this notebook we manually coded to understand how the flow works behind but this not right way to make a neural network in pytorch.
- Pytorch gives out box many components for training a model.

In [3]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

- Importing a dataset.

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

- Droping unneeded columns such as id and unnamed in this dataset.

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [8]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

- Train Test Split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

- Scaling

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 0.8998292 ,  1.22201756,  0.94582228, ...,  1.17259394,
         0.66725315,  2.7647761 ],
       [ 1.47668812, -0.810418  ,  1.45491153, ...,  0.98615513,
        -0.75624853, -1.1551491 ],
       [ 2.66519142,  1.73131086,  2.82650738, ...,  2.44710186,
         0.47908914,  0.22360594],
       ...,
       [-1.17280461, -0.43377784, -1.1490169 , ..., -0.73626439,
        -0.01831835, -0.37929053],
       [ 0.22151268, -0.57353739,  0.13338314, ..., -0.51131527,
        -0.6220794 , -0.83887554],
       [-0.26838259, -0.16610276, -0.24149167, ...,  1.46142127,
         1.62770773,  1.88623845]])

In [12]:
y_train

72     M
161    M
202    M
34     M
65     M
      ..
449    M
148    B
338    B
434    B
47     M
Name: diagnosis, Length: 455, dtype: object

- Label Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,

- Numpy arrays to pytorch tensors.

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor

tensor([[ 0.8998,  1.2220,  0.9458,  ...,  1.1726,  0.6673,  2.7648],
        [ 1.4767, -0.8104,  1.4549,  ...,  0.9862, -0.7562, -1.1551],
        [ 2.6652,  1.7313,  2.8265,  ...,  2.4471,  0.4791,  0.2236],
        ...,
        [-1.1728, -0.4338, -1.1490,  ..., -0.7363, -0.0183, -0.3793],
        [ 0.2215, -0.5735,  0.1334,  ..., -0.5113, -0.6221, -0.8389],
        [-0.2684, -0.1661, -0.2415,  ...,  1.4614,  1.6277,  1.8862]],
       dtype=torch.float64)

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [29]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad= True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

 - Important parameters

In [30]:
learning_rate = 0.1
epochs = 25

- Training pipeline

In [31]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 3.7451689254690517
Epoch: 2, loss: 3.631093762840063
Epoch: 3, loss: 3.5114203628443996
Epoch: 4, loss: 3.3835657571355124
Epoch: 5, loss: 3.250806546831748
Epoch: 6, loss: 3.116335892950041
Epoch: 7, loss: 2.982800389236233
Epoch: 8, loss: 2.8473833222480076
Epoch: 9, loss: 2.706572595906
Epoch: 10, loss: 2.561545268800743
Epoch: 11, loss: 2.414262960740123
Epoch: 12, loss: 2.261969681526811
Epoch: 13, loss: 2.105012287893291
Epoch: 14, loss: 1.949102824296064
Epoch: 15, loss: 1.7939676214833535
Epoch: 16, loss: 1.642162376876026
Epoch: 17, loss: 1.4988065477017238
Epoch: 18, loss: 1.3628496477869285
Epoch: 19, loss: 1.2382554909837704
Epoch: 20, loss: 1.1298877789096533
Epoch: 21, loss: 1.0392477228558732
Epoch: 22, loss: 0.9669665931905244
Epoch: 23, loss: 0.9121132841002778
Epoch: 24, loss: 0.8718024796037375
Epoch: 25, loss: 0.8424018915160661


In [32]:
model.weights

tensor([[ 0.5068],
        [ 0.0740],
        [ 0.0115],
        [-0.2761],
        [-0.2431],
        [-0.2437],
        [ 0.0481],
        [ 0.3474],
        [-0.1275],
        [ 0.4262],
        [ 0.1005],
        [ 0.1805],
        [ 0.1313],
        [-0.3831],
        [ 0.3963],
        [ 0.4892],
        [-0.2635],
        [-0.3215],
        [ 0.5120],
        [-0.0969],
        [ 0.0290],
        [ 0.3597],
        [ 0.1949],
        [-0.1604],
        [-0.1212],
        [-0.1327],
        [-0.3392],
        [ 0.3189],
        [ 0.5329],
        [-0.0150]], dtype=torch.float64, requires_grad=True)

In [33]:
model.bias

tensor([-0.1141], dtype=torch.float64, requires_grad=True)

### Evaluation

In [40]:
# model evaluation

with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5129270553588867
