# Pytorch basics

In [2]:
# import torch ( pytorch library )
import torch

- Checking the version of pytorch

In [3]:
# check the version
print(torch.__version__)

2.7.1+cpu


- Checking if cuda is available means gpu is available.

In [4]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU thank you.")

CUDA is not available. Using CPU thank you.


## Creating a tensor

In [5]:
# using empty
# just some garbage values
# can be different values at different times
a = torch.empty(3, 4)
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
# checking the type of tensor
print(a.type())

torch.FloatTensor


ZEROS
- generate zero values tensor

In [7]:
# creating a tensor with zero values
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

ONES
- generate one values tensor

In [8]:
# creating a tensor with one values
torch.ones(2, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

RAND
- generate random values between 0 and 1

In [9]:
# creating a tensor with random values
# values are between 0 and 1
torch.rand(3, 4)

tensor([[0.5902, 0.3886, 0.0365, 0.8438],
        [0.8314, 0.3827, 0.0115, 0.5459],
        [0.6480, 0.5533, 0.2756, 0.5847]])

In [10]:
torch.rand(3, 4)

tensor([[0.3987, 0.9425, 0.4205, 0.5798],
        [0.3801, 0.3612, 0.7194, 0.6735],
        [0.5768, 0.2619, 0.9350, 0.1763]])

SEED
- At some point of time we want all random values to be same in rand which not happens in rand normally
- For that we use seed.

In [11]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(10)
torch.rand(2, 3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [14]:
torch.manual_seed(10)
torch.rand(2, 3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

torch.tensor([1, 2, 3])
- torch.tensor([1, 2, 3], dtype=torch.float32)
- torch.tensor([1, 2, 3], dtype=torch.float64)
- torch.tensor([1, 2, 3], dtype=torch.float16)
- torch.tensor([1, 2, 3], dtype=torch.int32)
- torch.tensor([1, 2, 3], dtype=torch.int64)
- torch.tensor([1, 2, 3], dtype=torch.int16)

This is how we can create a tensor with a specific data type and values.

In [15]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

arange
- To create a range of values
- arange(start, end, step)

In [16]:
# Without step size
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# With step size
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

linspace (linearly spaced array)
- It is used to create a 1-D array with evenly spaced elements within a specified range.

In [18]:
# creating 10 evenly spaced values between 1 and 10
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
torch.linspace(1, 100, 20)
# creating 20 evenly spaced values between 1 and 100

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

EYE
- It creates a identity matrix which is also a diagonal and square matrix.
- It looks like this and can be of different dimensions.

[
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

In [20]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

full
- Creates a tensor of any size and fills it with value you give.

In [21]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor Shapes

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

- To check shape of a tensor

In [30]:
x.shape

torch.Size([2, 3])

- How to check some information about the tensor

In [24]:
# checking shape of a tensor
print(x.shape)

# checking the data type of a tensor
print(x.dtype)

# checking the device of a tensor
print(x.device)

torch.Size([2, 3])
torch.int64
cpu


- To make a tensor with any values but of same shape as another tensor, we can use torch.empty_like()

In [25]:
torch.empty_like(x)

tensor([[4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
# torch.rand_like(x)
'''
This will give an error because the given tensor is of integer data type and we are trying to create a tensor of random values which are of float data type.
'''

# To solve the problem we can change the data type of the given tensor to float
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

## Tensor data types

- To check the data type of a tensor, use the dtype attribute.

In [31]:
x.dtype

torch.int64

- Assign a data type, that can also be different from values

In [32]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

- Change the data type of existing tensor.

In [35]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])