# Using numpy with pytorch.

In [1]:
import torch
import numpy as np

- Converting pytorch tensor into numpy array.

In [2]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [3]:
b = a.numpy()
b

array([1, 2, 3])

In [4]:
type(b)

numpy.ndarray

- Converting numpy array to pytorch tensor.

In [5]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [6]:
torch.from_numpy(c)

tensor([1, 2, 3])