How to make tensors on gpu instead of cpu.

This notebook is made on google colab.

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU thank you.")

CUDA is available
Using GPU: Tesla T4


In [3]:
device = torch.device("cuda")

In [5]:
# creating a new tensor on gpu
a = torch.rand((2,3), device=device)
a

tensor([[0.3928, 0.9480, 0.8579],
        [0.8530, 0.6310, 0.6073]], device='cuda:0')

How to move a existing tensor to GPU

In [6]:
# moving an existing tensor on gpu
b = torch.rand(2,3)
b

tensor([[0.6825, 0.1868, 0.2238],
        [0.8721, 0.1910, 0.5492]])

In [7]:
b.to(device)

tensor([[0.6825, 0.1868, 0.2238],
        [0.8721, 0.1910, 0.5492]], device='cuda:0')

In [8]:
b + 5

tensor([[5.6825, 5.1868, 5.2238],
        [5.8721, 5.1910, 5.5492]])

Let's see we need gpu when it also works on gpu by measuring time of calculation.

In [9]:
import time

# define the size of the matrices
size =  10000 # large size so we can see a visible difference

# Create random matrices on CPU
mat_cpu1 = torch.rand(size, size)
mat_cpu2 = torch.rand(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(mat_cpu1, mat_cpu2)
end_time = time.time()
cpu_time = end_time - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to gpu
mat_gpu1 = mat_cpu1.to('cuda')
mat_gpu2 = mat_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(mat_gpu1, mat_gpu2)
end_time = time.time()
gpu_time = end_time - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 15.5911 seconds
Time on GPU: 0.1064 seconds
