# Reshaping Tensors

In [2]:
import torch

- To reshape a tensor we can use reshape() function.
- It's important to note that the product of the dimensions of the reshaped tensor must be equal to the number of elements in the original tensor. Otherwise, it will raise an error.

In [3]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

flatten
- It gives one dimensional array of original tensor.

In [5]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.9337, 0.7241, 0.4636, 0.6099],
         [0.6482, 0.5949, 0.2438, 0.9422],
         [0.8261, 0.7177, 0.2022, 0.9212]],

        [[0.0745, 0.3761, 0.1352, 0.1870],
         [0.5387, 0.2339, 0.7632, 0.4335],
         [0.6510, 0.3861, 0.0517, 0.8970]]])

permute
- We can change the order of the dimensions of a tensor.
- It does not change the values of the tensor.
- It just changes the order of the dimensions.

In [7]:
# permute
b.permute(2, 0, 1)

tensor([[[0.9337, 0.6482, 0.8261],
         [0.0745, 0.5387, 0.6510]],

        [[0.7241, 0.5949, 0.7177],
         [0.3761, 0.2339, 0.3861]],

        [[0.4636, 0.2438, 0.2022],
         [0.1352, 0.7632, 0.0517]],

        [[0.6099, 0.9422, 0.9212],
         [0.1870, 0.4335, 0.8970]]])

In [9]:
print(b.shape)
print(b.permute(2, 0, 1).shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


unsqueeze
- It adds a dimension to the tensor at the specified position.
- unsqueeze(dim)
- dim: dimension to be added

In [10]:
c = torch.rand(22, 23, 3)

In [12]:
c.unsqueeze(0).shape

torch.Size([1, 22, 23, 3])

In [13]:
c.unsqueeze(1).shape

torch.Size([22, 1, 23, 3])

squeeze
- Opposite of unsqueeze
- Removes the dimension of size 1

In [15]:
d = torch.rand(1, 20)
print(d.shape)
d.squeeze(0).shape

torch.Size([1, 20])


torch.Size([20])