# Tensor Operations

In [2]:
import torch

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
x_float = torch.rand(3, 3)
x_float

tensor([[0.2712, 0.9539, 0.1595],
        [0.0394, 0.9295, 0.7940],
        [0.3199, 0.3517, 0.1860]])

In [10]:
# addition
print(f"\nAddition: \n{x + 10}")

# subtraction
print(f"\nSubtraction: \n{x - 10}")

# multiplication
print(f"\nMultiplication: \n{x * 10}")

# division
print(f"\nDivision: \n{x / 10}")

# power
print(f"\nPower: \n{x ** 2}")

# integer division
# integer division means that the result will be an integer
print(f"\nInteger Division: \n{(x_float * 100) // 2}")

# modulus
print(f"\nModulus: \n{x % 2}")



Addition: 
tensor([[11, 12, 13],
        [14, 15, 16]])

Subtraction: 
tensor([[-9, -8, -7],
        [-6, -5, -4]])

Multiplication: 
tensor([[10, 20, 30],
        [40, 50, 60]])

Division: 
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

Power: 
tensor([[ 1,  4,  9],
        [16, 25, 36]])

Integer Division: 
tensor([[13., 47.,  7.],
        [ 1., 46., 39.],
        [15., 17.,  9.]])

Modulus: 
tensor([[1, 0, 1],
        [0, 1, 0]])


## Element-wise operations

In [11]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(f"\nA: \n{a}")
print(f"\nB: \n{b}")


A: 
tensor([[0.1024, 0.0502, 0.4127],
        [0.7942, 0.2612, 0.3498]])

B: 
tensor([[0.8156, 0.6370, 0.2155],
        [0.9404, 0.3565, 0.1911]])


In [12]:
# add
print(a + b)

# subtract
print(a - b)

# multiply
print(a * b)

# divide
print(a / b)

# power
print(a ** b)

# modulus
print(a % b)

tensor([[0.9180, 0.6872, 0.6282],
        [1.7347, 0.6177, 0.5409]])
tensor([[-0.7132, -0.5869,  0.1971],
        [-0.1462, -0.0953,  0.1586]])
tensor([[0.0835, 0.0320, 0.0889],
        [0.7469, 0.0931, 0.0668]])
tensor([[0.1256, 0.0788, 1.9147],
        [0.8445, 0.7328, 1.8301]])
tensor([[0.1559, 0.1486, 0.8263],
        [0.8052, 0.6197, 0.8181]])
tensor([[0.1024, 0.0502, 0.1971],
        [0.7942, 0.2612, 0.1586]])


abs
- to make all values positive
- absolute value

torch.abs(x)

In [14]:
c = torch.tensor([[-1, -2, 3], [4, -5, 6]])
torch.abs(c)

tensor([[1, 2, 3],
        [4, 5, 6]])

round
- To round off the values

In [16]:
d = torch.tensor([1.8, 2.3, 3.5, 4.7, 5.2, 6.4])
torch.round(d)

tensor([2., 2., 4., 5., 5., 6.])

ceil
- Go to next upper integer

In [17]:
torch.ceil(d)

tensor([2., 3., 4., 5., 6., 7.])

floor
- Opposite of ceil
- Goes down to the nearest (lower) integer

In [19]:
torch.floor(d)

tensor([1., 2., 3., 4., 5., 6.])

clamp
- All numbers will become in a specified range.
- torch.clamp(input, min, max)
- input: tensor to be clamped
- min: minimum value
- max: maximum value

Values less that min will be set to min
Values greater than max will be set to max
Values between min and max will remain the same

In [18]:
torch.clamp(d, min=2, max=5)

tensor([2.0000, 2.3000, 3.5000, 4.7000, 5.0000, 5.0000])

## Reduction Operation

In [29]:
e = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 5., 9.],
        [0., 5., 5.],
        [5., 1., 8.]])

In [30]:
#sum
torch.sum(e)

tensor(46.)

In [31]:
# sum along columns
torch.sum(e, dim=0)

tensor([13., 11., 22.])

In [32]:
# sum along rows
torch.sum(e, dim=1)

tensor([22., 10., 14.])

In [35]:
# mean
# but only works in float not integer
torch.mean(e)

tensor(5.1111)

In [36]:
# mean along columns
torch.mean(e, dim=0)

tensor([4.3333, 3.6667, 7.3333])

In [37]:
# median
torch.median(e)

tensor(5.)

In [38]:
# max and min
torch.max(e), torch.min(e)

(tensor(9.), tensor(0.))

In [39]:
# product
torch.prod(e)

tensor(0.)

In [40]:
# standard deviation
torch.std(e)

tensor(3.0596)

In [41]:
# variance
torch.var(e)

tensor(9.3611)

In [42]:
# argmax and argmin
# returns the index of the maximum (argmax) and minimum (argmin) values
torch.argmax(e), torch.argmin(e)

(tensor(2), tensor(3))

## Matrix Operations

In [43]:
f = torch.randint(size=(3, 3), low=0, high=10)
g = torch.randint(size=(3, 3), low=0, high=10)

print(f"\nF: \n{f}")
print(f"\nG: \n{g}")


F: 
tensor([[6, 8, 5],
        [1, 9, 5],
        [7, 5, 3]])

G: 
tensor([[9, 4, 3],
        [1, 1, 2],
        [2, 1, 7]])


In [44]:
# matrix multiplication
torch.matmul(f, g)

tensor([[72, 37, 69],
        [28, 18, 56],
        [74, 36, 52]])

In [45]:
vec1 = torch.tensor([1, 2])
vec2 = torch.tensor([3, 4])

# dot product
torch.dot(vec1, vec2)

tensor(11)

In [50]:
h = torch.randint(size=(3, 3), low=0, high=10)
h

tensor([[9, 0, 5],
        [6, 4, 0],
        [7, 0, 3]])

In [51]:
# transpose
h.T

tensor([[9, 6, 7],
        [0, 4, 0],
        [5, 0, 3]])

In [54]:
# determinant
# work only in float and square matrix
torch.det(h.float())

tensor(-32.0000)

In [55]:
# inverse
# work only in float and square matrix
torch.inverse(h.float())

tensor([[-0.3750,  0.0000,  0.6250],
        [ 0.5625,  0.2500, -0.9375],
        [ 0.8750, -0.0000, -1.1250]])

## Comparison Operations

In [56]:
i = torch.randint(size=(3, 3), low=0, high=10)
j = torch.randint(size=(3, 3), low=0, high=10)

print(f"\nI: \n{i}")
print(f"\nJ: \n{j}")


I: 
tensor([[9, 9, 3],
        [6, 0, 4],
        [0, 5, 6]])

J: 
tensor([[6, 1, 7],
        [4, 3, 2],
        [5, 6, 4]])


In [58]:
# greater than
print(i > j)
torch.gt(i, j)

tensor([[ True,  True, False],
        [ True, False,  True],
        [False, False,  True]])


tensor([[ True,  True, False],
        [ True, False,  True],
        [False, False,  True]])

In [59]:
# greater than or equal to
print(i >= j)
torch.ge(i, j)

tensor([[ True,  True, False],
        [ True, False,  True],
        [False, False,  True]])


tensor([[ True,  True, False],
        [ True, False,  True],
        [False, False,  True]])

In [60]:
# less than
print(i < j)
torch.lt(i, j)

tensor([[False, False,  True],
        [False,  True, False],
        [ True,  True, False]])


tensor([[False, False,  True],
        [False,  True, False],
        [ True,  True, False]])

In [62]:
# less than or equal to
print(i <= j)
torch.le(i, j)

tensor([[False, False,  True],
        [False,  True, False],
        [ True,  True, False]])


tensor([[False, False,  True],
        [False,  True, False],
        [ True,  True, False]])

In [63]:
# equal to
print(i == j)
torch.eq(i, j)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [64]:
# not equal to
print(i != j)
torch.ne(i, j)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## Special functions

In [74]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 7., 4.],
        [8., 9., 0.]])

In [75]:
# log
torch.log(k)

tensor([[2.0794, 1.9459, 1.3863],
        [2.0794, 2.1972,   -inf]])

In [76]:
# exp (exponents)
torch.exp(k)

tensor([[2.9810e+03, 1.0966e+03, 5.4598e+01],
        [2.9810e+03, 8.1031e+03, 1.0000e+00]])

In [77]:
# square root
torch.sqrt(k)

tensor([[2.8284, 2.6458, 2.0000],
        [2.8284, 3.0000, 0.0000]])

In [78]:
# absolute value
torch.abs(k)

tensor([[8., 7., 4.],
        [8., 9., 0.]])

In [79]:
# sigmoid 
torch.sigmoid(k)

tensor([[0.9997, 0.9991, 0.9820],
        [0.9997, 0.9999, 0.5000]])

In [80]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.1192, 0.9820],
        [0.5000, 0.8808, 0.0180]])

In [81]:
# relu
torch.relu(k)

tensor([[8., 7., 4.],
        [8., 9., 0.]])

## Inplace operations

In [82]:
m = torch.rand(3, 3)
n = torch.rand(3, 3)

print(f"\nM: \n{m}")
print(f"\nN: \n{n}")


M: 
tensor([[0.2994, 0.7281, 0.7782],
        [0.8131, 0.5290, 0.2375],
        [0.5961, 0.2977, 0.8015]])

N: 
tensor([[0.1398, 0.0273, 0.6364],
        [0.3886, 0.7269, 0.1695],
        [0.1164, 0.6254, 0.7985]])


In [89]:
'''
Note:-

When we perform this operation there is completly new tensor is created in the memory.
This is very in efficient for extremely large datasets.

So in pytorch we have in-place operations.
we can do this m.add_(n), with this m + n result is stored in m only no more memory consumed.
'''
m + n

tensor([[0.8588, 0.8372, 3.3240],
        [2.3674, 3.4368, 0.9157],
        [1.0617, 2.7995, 3.9955]])

In [90]:
m.add_(n)
m

tensor([[0.8588, 0.8372, 3.3240],
        [2.3674, 3.4368, 0.9157],
        [1.0617, 2.7995, 3.9955]])

In [88]:
n # will be same

tensor([[0.1398, 0.0273, 0.6364],
        [0.3886, 0.7269, 0.1695],
        [0.1164, 0.6254, 0.7985]])

In [93]:
torch.relu(m)

tensor([[0.8588, 0.8372, 3.3240],
        [2.3674, 3.4368, 0.9157],
        [1.0617, 2.7995, 3.9955]])

In [94]:
m

tensor([[0.8588, 0.8372, 3.3240],
        [2.3674, 3.4368, 0.9157],
        [1.0617, 2.7995, 3.9955]])

In [95]:
# instead to use permanent in-place operations we can use
m.relu_()
m

tensor([[0.8588, 0.8372, 3.3240],
        [2.3674, 3.4368, 0.9157],
        [1.0617, 2.7995, 3.9955]])

## Copying a tensor

In [3]:
a = torch.rand(2, 2)
a

tensor([[0.3032, 0.5001],
        [0.4288, 0.1224]])

In [4]:
b = a
b

tensor([[0.3032, 0.5001],
        [0.4288, 0.1224]])

In [5]:
a[0, 0] = 100
a, b

(tensor([[100.0000,   0.5001],
         [  0.4288,   0.1224]]),
 tensor([[100.0000,   0.5001],
         [  0.4288,   0.1224]]))

In [6]:
# instead of copying tensor it is storing the reference of the tensor
# so to avoid this we can use
c = a.clone()
c

a[0, 0] = 0
a, c

(tensor([[0.0000, 0.5001],
         [0.4288, 0.1224]]),
 tensor([[100.0000,   0.5001],
         [  0.4288,   0.1224]]))

In [7]:
# we can also find memory address of the tensor
print(hex(id(a)))
print(hex(id(b)))
print(hex(id(c)))

0x2b7eb180370
0x2b7eb180370
0x2b7eab90a00


In [8]:
id(a)

2988946490224