# Making a neural network using pytorch nn module

 The nn module
 
The torch.nnmodule in PyTorch is a core library that provides a wide array of classes and 
functions designed to help developers build neural networks efficiently and effectively. It 
abstracts the complexity of creating and training neural networks by offering pre-built layers, 
loss functions, activation functions, and other utilities, enabling you to focus on designing and 
experimenting with model architectures.

 Key Components of torch.nn:

 1. Modules (Layers):
 - nn.Module: The base class for all neural network modules. Your custom models and layers should subclass this class.

 - Common Layers: Includes layers like nn.Linear(fully connected layer), nn.Conv2d
 (convolutional layer), nn.LSTM(recurrent layer), and many others.

 2. Activation Functions:
 - Functions like nn.ReLU, nn.Sigmoid, and nn.Tanhintroduce non-linearities to the 
model, allowing it to learn complex patterns.

 3. Loss Functions:
 - Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLossto quantify the difference between the model's predictions and the actual targets.

 4. Container Modules:
 - nn.Sequential: A sequential container to stack layers in order. 

 5. Regularization and Dropout:
 - Layers like nn.Dropoutand nn.BatchNorm2dhelp prevent overfitting and improve the model's ability to generalize to new data.

In [1]:
import torch
import torch.nn as nn

In [16]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

- To make the above code shorter, we use sequential container.

In [19]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

- Instead of using model.forward(features) pytorch recommend to use model(features).
- There are magic functions, where on function name __call__ is overwritten in library so when anyone write this code it automatically call the forward function.

In [20]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3891],
        [0.4456],
        [0.3655],
        [0.4206],
        [0.4149],
        [0.3672],
        [0.4017],
        [0.4024],
        [0.4284],
        [0.4166]], grad_fn=<SigmoidBackward0>)

In [18]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.3812,  0.1684,  0.3070, -0.2405,  0.3661],
        [-0.3441, -0.0436,  0.2437, -0.1250,  0.2618],
        [-0.0993, -0.1461, -0.2978,  0.4303, -0.1071]], requires_grad=True)

In [6]:
model.linear2.weight

Parameter containing:
tensor([[-0.2158,  0.5577, -0.2940]], requires_grad=True)

In [7]:
# show model bias
model.linear1.bias

Parameter containing:
tensor([-0.4180, -0.3196, -0.1704], requires_grad=True)

In [8]:
model.linear2.bias

Parameter containing:
tensor([-0.3522], requires_grad=True)

In [10]:
!pip install torchinfo

In [11]:
from torchinfo import summary

In [12]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00