# Making a pipeline for model training in pytorch with nn module

## This code is done also manually but now rewritten with nn module useful functions outbox given by pytorch like:-


 1. Building the neural network using nn module
 2. Using built-in activation function
 3. Using built-in loss function
 4. Using built-in optimizer

In [14]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

- Importing a dataset.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

- Droping unneeded columns such as id and unnamed in this dataset.

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

- Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

- Scaling

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[-0.70463376, -1.4518307 , -0.71355321, ..., -0.44626437,
        -0.19415951,  0.25221707],
       [-1.47141513, -0.77594304, -1.36943705, ..., -1.15970048,
        -2.11580661, -0.36369592],
       [-0.2966482 ,  0.71934267, -0.39107698, ..., -1.61229766,
        -1.01257529, -1.48294208],
       ...,
       [-0.28507415, -1.22036233, -0.3616463 , ..., -1.20836851,
        -1.33513748, -1.04394026],
       [-0.63518941, -0.09542602, -0.56261583, ...,  0.64039663,
         3.21847985,  3.38777415],
       [ 0.18946225, -1.18795675,  0.29045361, ..., -0.03847588,
        -0.09979291,  0.52145564]])

In [8]:
y_train

98     B
116    B
178    B
358    B
13     M
      ..
136    B
267    B
309    B
31     M
421    B
Name: diagnosis, Length: 455, dtype: object

- Label Encoding

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,

- Numpy arrays to pytorch tensors.

In [10]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
X_train_tensor

tensor([[-0.7046, -1.4518, -0.7136,  ..., -0.4463, -0.1942,  0.2522],
        [-1.4714, -0.7759, -1.3694,  ..., -1.1597, -2.1158, -0.3637],
        [-0.2966,  0.7193, -0.3911,  ..., -1.6123, -1.0126, -1.4829],
        ...,
        [-0.2851, -1.2204, -0.3616,  ..., -1.2084, -1.3351, -1.0439],
        [-0.6352, -0.0954, -0.5626,  ...,  0.6404,  3.2185,  3.3878],
        [ 0.1895, -1.1880,  0.2905,  ..., -0.0385, -0.0998,  0.5215]],
       dtype=torch.float64)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [38]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


In [39]:
loss_function = nn.BCELoss() # BinaryCrossEntropy loss function

In [29]:
type(loss_function)

torch.nn.modules.loss.BCELoss

 - Important parameters

In [40]:
learning_rate = 0.1
epochs = 25

- Training pipeline

The torch.optim module

- torch.optim is a module in PyTorch that provides a variety of optimization
algorithms used to update the parameters of your model during training.

- It includes common optimizers like Stochastic Gradient Descent (SGD), Adam,
RMSprop, and more.

- It handles weight updates efficiently, including additional features like learning rate scheduling and weight decay (regularization).

- The model.parameters() method in PyTorch retrieves an iterator over all the
trainable parameters (weights and biases) in a model. These parameters are
instances of torch.nn.Parameter and include:

 -Weights: The weight matrices of layers like nn.Linear, nn.Conv2d, etc.

 -Biases: The bias terms of layers (if they exist).

- The optimizer uses these parameters to compute gradients and update them
during training.

In [41]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor.float()) # Cast to float32

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1).float()) # Cast target to float32

  # zero gradients
  optimizer.zero_grad() # It is suggested that clearing gradients should be before calculations

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 0.8667639493942261
Epoch: 2, loss: 0.6082367897033691
Epoch: 3, loss: 0.477849543094635
Epoch: 4, loss: 0.40445125102996826
Epoch: 5, loss: 0.357302725315094
Epoch: 6, loss: 0.32416868209838867
Epoch: 7, loss: 0.29940083622932434
Epoch: 8, loss: 0.2800476551055908
Epoch: 9, loss: 0.2644162178039551
Epoch: 10, loss: 0.25146448612213135
Epoch: 11, loss: 0.24051395058631897
Epoch: 12, loss: 0.23110276460647583
Epoch: 13, loss: 0.22290468215942383
Epoch: 14, loss: 0.21568232774734497
Epoch: 15, loss: 0.20925824344158173
Epoch: 16, loss: 0.20349697768688202
Epoch: 17, loss: 0.1982930302619934
Epoch: 18, loss: 0.19356298446655273
Epoch: 19, loss: 0.18923978507518768
Epoch: 20, loss: 0.18526892364025116
Epoch: 21, loss: 0.18160557746887207
Epoch: 22, loss: 0.17821243405342102
Epoch: 23, loss: 0.17505818605422974
Epoch: 24, loss: 0.17211638391017914
Epoch: 25, loss: 0.16936449706554413


In [42]:
model.linear.weight

Parameter containing:
tensor([[ 0.1070,  0.1284,  0.1295,  0.4044, -0.0090,  0.1597,  0.3821,  0.1932,
          0.0284,  0.0211,  0.3502, -0.0555,  0.1167,  0.2586,  0.0226, -0.0464,
         -0.1315, -0.0069, -0.1255, -0.1198,  0.1746,  0.2279,  0.2031,  0.3462,
          0.2570,  0.2007,  0.2170,  0.1745,  0.0510,  0.1875]],
       requires_grad=True)

In [43]:
model.linear.bias

Parameter containing:
tensor([-0.2911], requires_grad=True)

### Evaluation

In [44]:
# model evaluation

with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5236995816230774
